/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Contributors:   Mathias Bogaert

package org.apache.log4j.xml;

import org.apache.log4j.Layout;
import org.apache.log4j.spi.LoggingEvent;

/**
 * The output of the XMLLayout consists of a series of log4j:event
 * elements as defined in the <a
 * href="log4j.dtd">log4j.dtd</a>. It does not output a
 * complete well-formed XML file. The output is designed to be
 * included as an <em>external entity</em> in a separate file to form
 * a correct XML file.
 *
 * <p>For example, if <code>abc</code> is the name of the file where
 * the XMLLayout ouput goes, then a well-formed XML file would be:
 *
  <pre>
   &lt;?xml version="1.0" ?&gt;
 
  &lt;!DOCTYPE log4j:eventSet SYSTEM "log4j.dtd" [&lt;!ENTITY data SYSTEM "abc"&gt;]&gt;
 
  &lt;log4j:eventSet version="1.2" xmlns:log4j="http://jakarta.apache.org/log4j/"&gt;
 	&nbsp;&nbsp;&data;
  &lt;/log4j:eventSet&gt;
  </pre>
 
 * <p>This approach enforces the independence of the XMLLayout and the
 * appender where it is embedded.
 *
 * <p>The <code>version</code> attribute helps components to correctly
 * intrepret output generated by XMLLayout. The value of this
 * attribute should be "1.1" for output generated by log4j versions
 * prior to log4j 1.2 (final release) and "1.2" for relase 1.2 and
 * later.
 *
 * Appenders using this layout should have their encoding
 * set to UTF-8 or UTF-16, otherwise events containing
 * non ASCII characters could result in corrupted
 * log files. 
 *
 * @author Ceki  G&uuml;lc&uuml;
 * @since 0.9.0 
 * */
public class XMLLayout extends Layout {

  public void setLocationInfo(boolean flag) { }
  
  public boolean getLocationInfo() { return false; }

  public void setProperties(final boolean flag) { }

  public boolean getProperties() { return false; }

  public void activateOptions() { }

  public String format(final LoggingEvent event) { return ""; }

  public boolean ignoresThrowable() {
    return false;
  }
}
